set(ASSETS_DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Pandemonic)

file(COPY ${CMAKE_CURRENT_LIST_DIR}/assets DESTINATION ${ASSETS_DESTINATION})
file(COPY ${CMAKE_CURRENT_LIST_DIR}/shaders DESTINATION ${ASSETS_DESTINATION})
file(COPY ${CMAKE_CURRENT_LIST_DIR}/data DESTINATION ${ASSETS_DESTINATION})