set(EXECUTABLE_PATH ${CMAKE_CURRENT_BINARY_DIR}/Pandemonic)

if( WIN32 )
    SET(LIB_DIR "C:/msys64/mingw64/bin")
    file(COPY "${LIB_DIR}/libpng16-16.dll" DESTINATION ${EXECUTABLE_PATH})
    file(COPY "${LIB_DIR}/libbz2-1.dll" DESTINATION ${EXECUTABLE_PATH})
    file(COPY "${LIB_DIR}/libjsoncpp-24.dll" DESTINATION ${EXECUTABLE_PATH})
    file(COPY "${LIB_DIR}/libgcc_s_seh-1.dll" DESTINATION ${EXECUTABLE_PATH})
    file(COPY "${LIB_DIR}/libtinyxml2.dll" DESTINATION ${EXECUTABLE_PATH})
    file(COPY "${LIB_DIR}/libpng16-16.dll" DESTINATION ${EXECUTABLE_PATH})
    file(COPY "${LIB_DIR}/libwinpthread-1.dll" DESTINATION ${EXECUTABLE_PATH})
    file(COPY "${LIB_DIR}/libstdc++-6.dll" DESTINATION ${EXECUTABLE_PATH})
    file(COPY "${LIB_DIR}/zlib1.dll" DESTINATION ${EXECUTABLE_PATH})
endif( WIN32 )